version: '2.4'

services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    
    mem_limit: 300m
    env_file: .env
    environment:
      - TZ=UTC
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks: 
      ooNet:
        ipv4_address: 172.16.0.2
    labels:
      - traefik.enable=false

  s3:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    restart: unless-stopped
    volumes:
      - ./data/s3:/data
    env_file: .env
    command: server /data
    ## depending on network setup
    ports:
      - "9050:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://s3:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      ooNet:
        ipv4_address: 172.16.0.3
    labels:
      - traefik.enable=false

  server:
    image: openolitor/openolitor-server
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
    # server settings
      - ./config/server/openolitor-server.conf:/etc/openolitor-server/application.conf
      - ./config/server/openolitor-server-logback.xml:/etc/openolitor-server/logback.xml
      - ./log/server/:/var/log/openolitor-server/
    depends_on:
      - db
      - s3
    ports:
      - "9003:9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:9003/csa1/open/projekt"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks: 
      web:
      ooNet:
        ipv4_address: 172.16.0.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ool-server.entrypoints=https"
      - "traefik.http.routers.ool-server.rule=Host(`ool-server.ax9.eu`)"
      - "traefik.http.routers.ool-server.tls.certresolver=myhttpchallenge"

  client-admin:
    image: openolitor/openolitor-client-admin
    ports:
      - "9100:80"
    restart: unless-stopped
    volumes:
      - ./config/client/admin/config.js:/usr/share/nginx/html/environments/config.js
    networks: 
      web:
      ooNet:
        ipv4_address: 172.16.0.5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ool-admin.entrypoints=https"
      - "traefik.http.routers.ool-admin.rule=Host(`ool-admin.ax9.eu`)"
      - "traefik.http.routers.ool-admin.tls.certresolver=myhttpchallenge"

  client-kundenportal:
    image: openolitor/openolitor-client-kundenportal
    ports:
      - "9110:80"
    restart: unless-stopped
    volumes:
      - ./config/client/kundenportal/config.js:/usr/share/nginx/html/environments/config.js
    networks: 
      web:
      ooNet:
        ipv4_address: 172.16.0.6
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ool.entrypoints=https"
      - "traefik.http.routers.ool.rule=Host(`ool.ax9.eu`)"
      - "traefik.http.routers.ool.tls.certresolver=myhttpchallenge"

  pdf-tool:
    image: eugenmayer/jodconverter:rest
    restart: unless-stopped
    ports:
      - "9040:8080"
    networks: 
      ooNet:
        ipv4_address: 172.16.0.8

  smtp-proxy:
    image: mailhog/mailhog
    environment:
      - TZ=UTC
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: 
      web:
      ooNet:
        ipv4_address: 172.16.0.9
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.ool-smtp-proxy.entrypoints=https"
    - "traefik.http.routers.ool-smtp-proxy.rule=Host(`ool-smtp-proxy.ax9.eu`)"
    - "traefik.http.routers.ool-smtp-proxy.tls.certresolver=myhttpchallenge"


networks:
  ooNet:
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
  web:
    external: true
